application: github-data-challenge
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: dataviz/static/js

- url: /css
  static_dir: dataviz/static/css

- url: /img
  static_dir: dataviz/static/img

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
